#Tidligere kalt joint controller
boat_robot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 60

  # Controller
  C1:
    type: position_controllers/JointPositionController
    joint: J1
    pid: {p: 10.0, i: 10.0, d: 1.0}
  # Controller
  C2:
    type: position_controllers/JointPositionController
    joint: J2
    pid: {p: 10.0, i: 10.0, d: 1.0}
 # Controller
  C3:
    type: position_controllers/JointPositionController
    joint: J3
    pid: {p: 10.0, i: 10.0, d: 1.0}

  # Controller
  C4:
    type: position_controllers/JointPositionController
    joint: J4
    pid: {p: 10.0, i: 10.0, d: 1.0}

  # Controller
  C5:
    type: position_controllers/JointPositionController
    joint: J5
    pid: {p: 10.0, i: 10.0, d: 1.0}

  # Controller
  C6:
    type: position_controllers/JointPositionController
    joint: J6
    pid: {p: 10.0, i: 10.0, d: 1.0}


  mobile_base_controller:
    type: "diff_drive_controller/DiffDriveController"
    left_wheel: left_wheel_joint
    right_wheel: right_wheel_joint
    wheel_separation: 0.3
    wheel_radius: 0.1018
    cmd_vel_timeout: 0.5
    enable_odom_tf: true
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    base_frame_id: ShipBodyLink
